### ISSUE TITLE
Wes's avatar is squished

### ISSUE THREAD

**Issue by cfsanderson** [wesbos/Syntax#108]
Wes's avatar is squished when when visiting the site from a link to an episode. 
It's seems to be happening on latest Chrome and Firefox, haven't checked others.
I'm on MacBook Pro with 10.13.5

![image](https://user-images.githubusercontent.com/20695956/42837855-3cbe15d6-89cd-11e8-9ec0-11b098aaa85d.png)

**Comment by wesbos** [comment]
fixed :D
