### ISSUE TITLE
Scroll to top after clicking on an episode

### ISSUE THREAD

**Issue by simeydk** [wesbos/Syntax#138]
This is a nice-to-have proposed improvement.

Now that the list of episodes is getting longer, the experience when clicking on an older episode is not great. Most users would do this with the intent of reading the shownotes for that episode, presumably from the start. However, when clicking on an older episode far down the list, the scroll position remains far down and the user has to scroll all the way back up by hand (see GIF below) #firstworldproblems.

Proposed solutions: 

- Add a "scroll to top" button; and/or 
- automatically scroll to top when a user clicks on an episode, and/or
- separate scrolling for episode list and shownotes

![syntax scroll to top](https://user-images.githubusercontent.com/13088589/44645872-8211c480-a9d9-11e8-84d0-82aa847d026d.gif)

**Comment by simeydk** [comment]
I would be keen to have a stab at implementing something for this, if you're keen to make a change here. If so, which solution would you prefer? 

(Naturally, you are also most welcome to close this issue if you're not phased by this)

**Comment by drubiodev** [comment]
@simeydk yeah wouldn't be a bad improvement, I was thinking maybe having a fixed height for the list of episodes and info. This way when you click on a episode the info list would scroll independent from the episode list.

**Comment by wesbos** [comment]
would be great :)

**Comment by ClayBenson94** [comment]
If nobody else is looking at this, I'd love to give this a shot :)

**Comment by simeydk** [comment]
> If nobody else is looking at this, I'd love to give this a shot :)

I offered to give it a stab before, but am not getting round to it, so happy to "give it up" (if I ever had it). The maintainers seem keen so I would think it's fine.

**Comment by simeydk** [comment]
I just saw @legarland submitted a PR for this, #113 (a month before I opened the issue!)

**Comment by JohanG2012** [comment]
I just noticed this as well, would be great!

**Comment by jameygleason** [comment]
This what you where thinking?

![2e7d6b84cd90d42bf0e4c74ea3dc395b](https://user-images.githubusercontent.com/30030613/46631793-76580880-cb16-11e8-9c01-fb19df6c4c33.gif)

**Comment by 416serg** [comment]
@jameygleason would you be able to scroll it to the top of `<main />`. That's where the player starts and I think that would be a better experience for users.

**Comment by legarland** [comment]
Check out my PR #113 to see if the experience fits this issue. I noticed this a while back and decided to add the smooth scrool functionality.

**Comment by jameygleason** [comment]
> @jameygleason would you be able to scroll it to the top of `<main />`. That's where the player starts and I think that would be a better experience for users.

Yeah totally. Give me an hour or so.

**Comment by jameygleason** [comment]
> Check out my PR #113 to see if the experience fits this issue. I noticed this a while back and decided to add the smooth scrool functionality.

@legarland looks good. I'm interested in knowing more about the polyfill.

**Comment by jameygleason** [comment]
Would someone be interested in looking at the polyfill and make sure I did that right?

![a902160c829ea1a9f4a3b67e5d0182c3](https://user-images.githubusercontent.com/30030613/46638466-030ec080-cb2f-11e8-95ab-33bf70a0ddde.gif)

**Comment by jameygleason** [comment]
Alright, I think I got it. Share your thoughts.

#184

![cfac0ff45c8c9d08c640869050a6d896](https://user-images.githubusercontent.com/30030613/46682914-d1443b00-cbbc-11e8-9847-493618380357.gif)

**Comment by csellis** [comment]
No longer an issue.
