### ISSUE TITLE
Convert to Next 7

### ISSUE THREAD

**Issue by wesbos** [wesbos/Syntax#156]

**Comment by jzabala** [comment]
I @wesbos I can try this one :D

I'll keep you posted if anything comes up.

**Comment by simeydk** [comment]
@wesbos you've mentioned considering moving the website to Netlify on the Podcast before (with Gatsby? or Next's Static Site Generator?). Is this a serious consideration, or is staying on Next+Now preferred?(perhaps from an if-its-not-broken-don't-fix-it point of view?)

**Comment by simeydk** [comment]
@jzabala  I'm not trying to intercept your offer to work on this. 

I'm actually fishing for some commentary from @wesbos (in this issue thread, or on the Podcast?) on what's the best fit here. Netlify is a friend of a show and is clearly awesome. However, the power of a Node app is still valuable. (I've also submitted a potluck question on this)

**Comment by jzabala** [comment]
yeah, don't worry @simeydk. I get it. I think your comment is very valuable and if they are planning to move to Gatsby, it will be a waste of time moving the site to Next.js 7. I think we probably should wait for @wesbos answer on this. What do you think?

**Comment by wesbos** [comment]
Yeah we currently use the node backend as an API to pull show notes from - it could be done as a static site but I think having a node backend will at some point be useful to us as well. 

so lets keep it on Next :D

**Comment by jzabala** [comment]
Created a PR for this issue (#167).

**Comment by 416serg** [comment]
@jzabala commented in the PR, time flies and so do NextJS updates, it's at `7.0.2` now 😅
