### ISSUE TITLE
convert to Styled Components

### ISSUE THREAD

**Issue by wesbos** [wesbos/Syntax#157]

**Comment by d-ivashchuk** [comment]
Hey, @wesbos what exactly do you need to convert?

**Comment by wesbos** [comment]
All the current CSS is in stylus - so it could be converted all at once or just component by component. I think its currently in BEM so it should be pretty easy

**Comment by d-ivashchuk** [comment]
I will work on that

**Comment by jameygleason** [comment]
I have everything converted in this fork branch. I still need to set up the server rendering of the styles.

https://github.com/jameygleason/Syntax/tree/styled-components

**Comment by jameygleason** [comment]
PR #185 
Converted Stylus to Styled Components and added a `_document.js` component with `ServerStyleSheet` for server rendering. Next step will be moving the global injection to the actual components.

**Comment by jameygleason** [comment]
@wesbos what's happening with the 💪? 

```@font-face {
  font-family: '💪';
  src:  url('/static/fonts/Radnika-Bold.woff2') format('woff2'),
        url('/static/fonts/Radnika-Bold.woff') format('woff')
}

h1,h2,h3,h4,h5,h6 {
  font-family: '💪';
  font-weight: 100;
}```

https://github.com/jameygleason/Syntax

**Comment by bchiang7** [comment]
@d-ivashchuk https://github.com/d-ivashchuk/Syntax/pull/2

**Comment by s-r-aman** [comment]
Hey! Can I also contribute to this? I know styled components pretty well. But I am new to contributing. Please help me what I need to do? @d-ivashchuk @416serg @wesbos.

**Comment by Nytheneals** [comment]
I would like to contribute to this too @d-ivashchuk @416serg @wesbos. , how can i help

**Comment by ckujawa** [comment]
Hi! Just curious...any progress on this? I ask because I'm working on the pagination issue and want to use styled components...but noticed that it's not yet been installed.
