### ISSUE TITLE
Fix layout on mobile

### ISSUE THREAD

**Issue by wesbos** [wesbos/Syntax#158]
Right now there are too many shows to scroll through to get to the show notes. We somehow need to fix this layout on mobile so its easier to navigate. Open to suggestions :)

**Comment by Martin-Pitt** [comment]
Shouldn't the order be switched?

The current show you are playing right now is primary vs. other shows being secondary.

**Comment by wuz** [comment]
I can take this issue. How do you feel about collapsing the rest of the shows behind an accordion?

**Comment by wesbos** [comment]
I think putting the show list first to show 3-5 show and overflow:scroll; on that would be good

Then the show notes below it
