### ISSUE TITLE
Make audio progress scrubber keyboard accessible 

### ISSUE THREAD

**Issue by wesbos** [wesbos/Syntax#159]

**Comment by stufinn** [comment]
I'd love to take a shot at this one. Just to clarify, scrubbing refers to the audio speed/fastness as opposed to the progress bar, right?

**Comment by tusharkhatiwada** [comment]
I would love to try this.
Do you mean by using **Left** and **Right** key to **Forward** and **Rewind** respectively? If yes, by how much second?

**Comment by tusharkhatiwada** [comment]
Created a pull request. But I'll update it with your requirements.

**Comment by tusharkhatiwada** [comment]
#161
