### ISSUE TITLE
Overcast doesn't include show notes. 

### ISSUE THREAD

**Issue by jwithington** [wesbos/Syntax#16]
See screenshot here. 

Thanks! This show is rad!

![Overcast screenshot](https://user-images.githubusercontent.com/4213550/28691449-d40826fc-72d1-11e7-879a-1739992e6079.PNG)

**Comment by ink8bit** [comment]
The same issue in iTunes too.

**Comment by stolinski** [comment]
This one might have been my fault. I published in LIbsyn before the notes were complete. I've added them now and am republishing.

**Comment by ink8bit** [comment]
@stolinski Thank you! Podcast description in iTunes is ok now!

**Comment by jwithington** [comment]
Yup, working in Overcast (once i redownloaded the episode)now!

Also: sorry about GIANT SCREENSHOT. Thanks Retina screen! 😆

**Comment by wesbos** [comment]
thaaanks scott
