### ISSUE TITLE
Add an accessible skip to content link 

### ISSUE THREAD

**Issue by wesbos** [wesbos/Syntax#160]

**Comment by roebuk** [comment]
Hey!

I'll happily take this. @wesbos which container do you you think is best to jump to? The `.show-wrap` div seems reasonably sensible.

**Comment by chadfawcett** [comment]
This should be closed as it's resolved by #163

**Comment by wesbos** [comment]
Would that provide any real benefit? Is there any downside to re-painting that is real?

**Comment by garyb1** [comment]
Yeah I suppose it's not really worth considering in this case .. I just said I would mention it that is all

**Comment by wesbos** [comment]
Definitely - you can send a PR if you'd like though - it's an interesting little bit of info :)

**Comment by garyb1** [comment]
Will do. Thanks wes
