### ISSUE TITLE
Adding meta description to meta.js

### ISSUE THREAD

**Issue by 416serg** [wesbos/Syntax#178]
Even though there is `og:description`, we still need a `description` meta tag. Referencing the lighthouse audit bellow.

<img width="627" alt="screen shot 2018-10-08 at 6 17 39 pm" src="https://user-images.githubusercontent.com/3760543/46636773-6bf23a80-cb27-11e8-9601-933914201df4.png">

Fixed in [#177](https://github.com/wesbos/Syntax/pull/177)

**Comment by 416serg** [comment]
@jumplottahigh I am not sure if you read the full issue, but I resolved it myself in #177 😅

**Comment by jumpalottahigh** [comment]
@416serg My bad didn't notice there was an open PR for this already.

**Comment by 416serg** [comment]
@jumpalottahigh all good! just don’t want Wes or Scott or whoever is going through the PRs to see dups or people to do twice the work, no matter how small that amount of work is 😅👍🏼

**Comment by jumpalottahigh** [comment]
@416serg Makes sense. Not easy, the life of open source maintainers :)

**Comment by 416serg** [comment]
speaking of which, @wesbos or @stolinski, let me know if you guys need a hand going through some of the PRs, with Hacktoberfest too, I can imagine there being a lot of attention on your amazing open source work 😊
