### ISSUE TITLE
[Request] Links in Show Notes to open in new tab

### ISSUE THREAD

**Issue by rclanan** [wesbos/Syntax#19]
Can we get the links in the show notes to open in a new tab? 
When listening to a show and wanting to view the notes and follow some of the links, it opens in the same window rather than a new tab, so you lose the spot in the show.

**Comment by wesbos** [comment]
Yeah this is a good idea. If anyone wants to take a stab at this after markdown parses it, that would be cool!

**Comment by rclanan** [comment]
The markdown package you are using allows you to specify custom render options: 

https://github.com/chjj/marked#overriding-renderer-methods
https://github.com/chjj/marked#inline-level-renderer-methods

For anyone that wants to take this. If it doesn't get picked up, I might take a look at it later this evening.

**Comment by dfosco** [comment]
@JonAbrams The default browser behavior is just that — the _default_ behavior. It can and should be changed when the context requires it.

**Comment by rclanan** [comment]
I would disagree @JonAbrams , from a user experience perspective, I wouldn't want a user that is listening to the podcast to be following along with the products I am referring to, click a link and lose their spot in the podcast. 

As much as that is the default browser experience, the default user experience from what I run into when linking to outbound links is typically in a new tab.

**Comment by JonAbrams** [comment]
I didn't realize this stops the playing of the podcast, my bad. Opening in a new tab makes sense in this context.

**Comment by JonAbrams** [comment]
I just assumed everyone listens on their phone, I totally missed your perspective.

**Comment by deepakkarki** [comment]
#20 Hey can someone review this :)

**Comment by wesbos** [comment]
Thanks everyone! It's all working and merged now :)

**Comment by rclanan** [comment]
Wow, that was a quick turn around. Great job!

**Comment by wesbos** [comment]
🎵 The power of open source 🎵
