### ISSUE TITLE
Both yarn.lock and package-lock.json exist

### ISSUE THREAD

**Issue by EricLemieux** [wesbos/Syntax#193]
Both `yarn.lock` and `package-lock.json` exist in the project root, only one needs to exist.

README recommends using `npm` and the `package-lock.json` has a longer git history. The yarn.lock file should be removed.

**Comment by jackmcpickle** [comment]
![screen shot 2018-10-13 at 9 07 30 am](https://user-images.githubusercontent.com/89775/46896988-9ba69700-cec7-11e8-84e5-69aa9ab953d2.png)

I'm a yarnpkg fan but consistency is better. Having 2 lock files makes it hard to keep both in line...
