### ISSUE TITLE
Add Renovate support for auto deps update. and tests?

### ISSUE THREAD

**Issue by jackmcpickle** [wesbos/Syntax#197]
I've added https://renovatebot.com/ to all my open source projects helps keep things upto date. 

Might be a good idea here too for a site that you want to keep the build deps updated. They support both types of lock files too. 

But probably good to add some tests...? 
Happy to help with that. But probably want some help deciding on a testing framework? Jest?

**Comment by 416serg** [comment]
@jackmcpickle let us know if you're up to implement some tests! Both @wesbos and @stolinski have courses on testing in React so it could be a good tool to get this done for Syntax!

[Wes's course](https://advancedreact.com/)
[Scott's course](https://www.youtube.com/watch?v=esVwR4lGwQE&list=PLLnpHn493BHEqP3gD1pCJYhxX6v2gBZzj) - and I believe advanced react testing is coming soon

**Comment by mendaomn** [comment]
Would love to help out with testing! What components or use cases would make the most sense to start with?

As per the tech, I'd use Jest and [Testing-library](https://testing-library.com) for units and maybe integration. Also, [Cypress](https://cypress.io) is a good option for integration and end-to-end!

**Comment by stolinski** [comment]
This kinda goes with #937 I think we can close this issue and move testing and update mangement in separate issues.
