### ISSUE TITLE
Add Now-Github integration to Syntax Repo

### ISSUE THREAD

**Issue by simeydk** [wesbos/Syntax#205]
Zeit added Github integration to Now in June 2018.

[https://zeit.co/blog/now-for-github](https://zeit.co/blog/now-for-github)

This automatically creates a new deploy of the site with every PR, which can be very handy to review PRs quickly.

**Comment by 416serg** [comment]
Looks like I don't have permissions to install apps on the repo! @wesbos this might be a good thing to look into and seems pretty easy to implement!

**Comment by simeydk** [comment]
Vercel integration is up and running
