### ISSUE TITLE
Hide horizontal scrollbar when not in use

### ISSUE THREAD

**Issue by Pixelrobin** [wesbos/Syntax#215]
I'm using Chrome on Windows 10. When making the screen smaller, it shows a disabled horizontal scrollbar.

![image](https://user-images.githubusercontent.com/17094139/47393276-e39d9900-d6d3-11e8-91fd-55686136acca.png)

I personally think it doesn't look all that great so I suggest instead of setting `overflow-x: scroll` to `overflow-x: auto` so the scrollbar only appears if it needs to.

I would love to do it myself for an easy hacktoberfest point (heh), but is it ok to proceed with a PR?

**Comment by 416serg** [comment]
@Pixelrobin Hey Michael 👋🏼 Good catch! I think that the author of that commit meant to put `overflow-y: scroll` as opposed to `overflow-x` since the X-axis never actually scrolls there.

If you want, submit a PR that fixes this issue and grab that Hacktoberfest point! 😃

**Comment by Pixelrobin** [comment]
Alright, I'll take it! I think auto would be better because on super tiny sizes (that are honestly kind of unrealistic), it does actually need to scroll a bit.

**Comment by simeydk** [comment]
I think this issue can be closed as the fix has been merged in #220.

**Comment by Pixelrobin** [comment]
Oh yeah, sorry about that.
