### ISSUE TITLE
Double @media query in header

### ISSUE THREAD

**Issue by bartveneman** [wesbos/Syntax#229]
I found a double `max-width: 670px` in https://github.com/wesbos/Syntax/blob/5bbfc5ef778639af800a3e8ea174cecb13a3c33a/styles/_header.styl#L68-L77 while running Syntax.fm through Project Wallace: https://www.projectwallace.com/teamwallace/syntaxfm/imports/20181103144312413. I guess this extra MQ could be removed, as well as the resets above this nested MQ.

**Comment by markpesantes** [comment]
If this is deemed as an issue I'd love to practice a PR and delete lines 75-77 =)

**Comment by luisbaugusto** [comment]
#341 fixes the stylesheet and removes the redundant CSS
