### ISSUE TITLE
Persist playbackRate and volume property

### ISSUE THREAD

**Issue by wesbos** [wesbos/Syntax#234]
Right now if I close the window and come back, the place is restored from localStorage, but the playbackRate and volume aren't. We should put these in localStorage when changed and then restore them when we mount the player

**Comment by ianizaguirre** [comment]
I will work on this

**Comment by ianizaguirre** [comment]
@wesbos , Submitted [pull request](https://github.com/wesbos/Syntax/pull/237) 😄

**Comment by MattSidor** [comment]
The playbackRate is being correctly stored in localStorage, but for some reason the video player still plays at 1x speed when you close the window and come back, play a different video in the playlist, or reload the page.

**Comment by ianizaguirre** [comment]
@MattSidor 

Hi Matt,

I am not seeing this behavior on my end, I am seeing everything being correctly restored when I exit the browser or reload the page - For me, the page speed, and volume bars are restored too my last saved settings.

For reference, I tried the steps you listed using Google Chrome, on my Macbook Pro.  

* Can you test this again?

Also, What browser (and browser version), are you using that is showing this behavior? And on Mac or Windows?

**Comment by MattSidor** [comment]
Thanks for the feedback @ianizaguirre and trying to help me figure this out!

I realized that I am running a Chrome extension called Video Speed Controller (https://github.com/igrigorik/videospeed) that was overriding the playbackRate setting. Disabling the extension has fixed it for me.

Sorry for the false alarm!
