### ISSUE TITLE
Push Notifications for new shows

### ISSUE THREAD

**Issue by wesbos** [wesbos/Syntax#240]
This is gonna get into service workers. It seems a large percentage of our listens come from Chrome web users. It would be neat to have an opt-in subscribe button (not an annoy on-load ask) that would push a notification each time a new episode is published.

**Comment by s-r-aman** [comment]
Hey @wesbos! Can you tell how you publish your podcast. We need trigger of some kind where we can know that a new podcast is published.

**Comment by wesbos** [comment]
The show is published via libsyn and via this application. It doesnt go live on the site until the Date.now() > show.publishDate 

So we could pretty easily code a check or cron job to fire something when a new episode is live.

The challenge is that we would need to maintain a database of push ids from people who have subscribed:

https://twitter.com/wesbos/status/1067473482525622272

**Comment by s-r-aman** [comment]
So are up to database thing?
