### ISSUE TITLE
having pagination instead of long scroll 

### ISSUE THREAD

**Issue by hozefaj** [wesbos/Syntax#291]
As the number of episodes increases, the page will get longer and longer. This will cause a very long scroll each way.

It would make sense to having pagination, showing maybe like 15 episodes per page.

**Comment by ckujawa** [comment]
Hey guys...I'm taking a look at this. I think the pagination is a great idea (if you think otherwise, let me know...and let me know how else I might be able to help)

**Comment by ckujawa** [comment]
hey @wesbos...I'm thinking of doing this and allowing people to set their preffered "page size", but want to keep the state of ShowList within ShowList itself instead of pulling it all the way back out to Index...so something like this:

```
let beginSliceAt = 0;
let pageSize = 11;

const getShortList = shows => {
  return shows.slice(beginSliceAt, pageSize);
};

const ShowList = ({
  shows,
  currentPlaying,
  currentShow,
  setCurrentPlaying
}) => (
  <div className="showList">
    {getShortList(shows).map(show => (
```

Your thoughts?

**Comment by ckujawa** [comment]
Submitted PR #399 as a solution to this. Can't seem to attach it to this issue though.

**Comment by stolinski** [comment]
Closing due to PR comment in #399
