### ISSUE TITLE
Heading levels

### ISSUE THREAD

**Issue by bripmccann** [wesbos/Syntax#318]
1. In the show notes, **the episode title and section headings are all `<h2>`s.** I checked out the site recently _looking_ for the show notes and scrolled right past. I guess I was looking for a visually distinct heading to mark the title. (And I'm sure there are accessibility issues you know about better than me.)
2. **There's no `<h1>` on the page.** An `<h1>` was added around the logo in #126 but removed in #190.

**Comment by 416serg** [comment]
@bripmccann feel free to submit a PR to make the show notes title an `h1` - pages definitely need an h1 for accessibility and defining the page structure and content hierarchy, not sure what to do about visually making the Show Notes more distinct

**Comment by sealedHuman** [comment]
@416serg would this amount to changing the Show Notes from "##" to "#" in each show's markdown file?

**Comment by 416serg** [comment]
Nope, should be simple, just editing the https://github.com/wesbos/Syntax/blob/master/components/ShowNotes.js file and changing the `h2` for `show.title`

**Comment by sealedHuman** [comment]
That works for the show's title, but I thought the idea was to change it for the "Show Notes" header, too. Looks like that is pulled into ShowNotes.js in the `dangerouslySetInnerHTML` at [https://github.com/wesbos/Syntax/blob/master/components/ShowNotes.js#L32](https://github.com/wesbos/Syntax/blob/master/components/ShowNotes.js#L32)
