### ISSUE TITLE
Shownotes box height < Show list height

### ISSUE THREAD

**Issue by simeydk** [wesbos/Syntax#32]
There currently is a max-height value (of 800px) on the shownotes component, but nothing corresponding on the list of shows. This didn't have an impact initially, but as the list of shows have increased to be longer than 800px, this results in a funny layout, where shownotes gets cut off before the end of the episode list.

![image](https://user-images.githubusercontent.com/13088589/33020441-0345acce-ce07-11e7-9e58-514989634627.png)

**Comment by simeydk** [comment]
Hi Wes & Scot

I noticed this (funny?) behavior on the Syntax website. If this isn't intentional, it could be fixed by either putting the same max-height on the showlist and the shownotes, or removing the max-height on the shownotes.

If this is something you want changed, I'd like to try fixing it. I haven't submitted a PR on github before, and this one looks small enough to be a good one to start with.

**Comment by wesbos** [comment]
Hey! I think it's probably best to take the max height off and just let the height be determined by either the shownotes or the list of shows - would be great if you could submit a PR . thanks!
