### ISSUE TITLE
Broken Links

### ISSUE THREAD

**Issue by ycchi** [wesbos/Syntax#335]
Hi Wes & Scott,

Thanks for the great podcast. 
I'm a web dev student and really enjoy your show.

I found a couple of broken links on ep. 140.
It seems like both of them are missing 'https://' in the url. 
Please refer to the screenshot below.

![Screen Shot 2019-05-07 at 10 46 10 PM](https://user-images.githubusercontent.com/44580684/57345802-427baa80-711a-11e9-8ef3-efd5cb7a237f.png)

once again, thanks for the great podcast and your contributions.

**Comment by bripmccann** [comment]
This has been a consistent issue, so you all would probably wanna know about this: @wesbos, @stolinski (@avclark?)

There are a few pending PRs fixing individual episodes.

**Comment by avclark** [comment]
@wesbos this is fixed on our end. i just submitted a PR with some fixes.

**Comment by bripmccann** [comment]
If you wanna accept the fixes that were already submitted:

Episode 140: #331 
Episode 142: #339 
Episode 146: #349 
Episode 150: #354 (duplicates: #355, #356, #357)

#360 takes care of episodes 148 & 152. (144 apparently didn't have a problem)
