### ISSUE TITLE
Unexpected search engine linking

### ISSUE THREAD

**Issue by jeffgreendesign** [wesbos/Syntax#364]
Seeing some unexpected behavior when searching for an episode's page on DuckDuckGo and Google. 

## DuckDuckGo

When I looked up the show "SVGs with Sara Soueidan" on DuckDuckGo, I get the correct show content in the search result but the link is to just https://syntax.fm/. To me, expected link would be https://syntax.fm/show/154/svgs-with-sara-soueidan.

![Screen Shot 2019-06-26 at 11 56 25 AM](https://user-images.githubusercontent.com/1553741/60195642-71082e80-9809-11e9-842a-7bc53a901f83.png)

## Google

With Google, I don't get any syntax.fm results initially.

![Screen Shot 2019-06-26 at 11 57 27 AM](https://user-images.githubusercontent.com/1553741/60195737-a1e86380-9809-11e9-9165-94327104a793.png)

Searching "SVGs with Sara Soueidan syntax.fm" I get some results but not to the episode page on syntax.fm. 

![Screen Shot 2019-06-26 at 11 59 32 AM](https://user-images.githubusercontent.com/1553741/60195877-f390ee00-9809-11e9-9e6c-2bc83d83f68e.png)

## Conclusion

I realize these may be two separate issues and might be more search optimization versus technical issues with the site. Thanks!

**Comment by 416serg** [comment]
Following up on this issue

Google: 

<img width="820" alt="Screen Shot 2019-10-22 at 11 35 00 PM" src="https://user-images.githubusercontent.com/3760543/67355218-b8d36400-f524-11e9-8de6-9ba9f5694071.png">

DuckDuckGo:

<img width="804" alt="Screen Shot 2019-10-22 at 11 35 24 PM" src="https://user-images.githubusercontent.com/3760543/67355228-bd981800-f524-11e9-94c0-0e76eb0d0754.png">

I made some changes to the head component, not sure if that's what caused it. PS on google, without `syntax` keyword, the episode shows up on the second page, i guess that's just the page rank quality in Google at this point 🤷‍♂
