### ISSUE TITLE
Add youtube-style timestamp queries

### ISSUE THREAD

**Issue by simeydk** [wesbos/Syntax#375]
I propose adding a feature to accept an optional query string on show links that starts playback at a specific timestamp, similar to Youtube. E.g. you would be able to go click on `syntax.fm/show/121/hasty-treat-tips-to-succeed-on-youtube?t=23m17s` (note the `?t=23m17s`) and be taken to the show's page (as before), but also have playback start at 23 minutes 17 seconds.

This would enable
* being able to link to specific timestamps from elsewhere (like twitter)
* Making timestamps in shownotes clickable links that jump the player to that point

I would like to attempt this. Would you be interested in merging this feature?

**Comment by simeydk** [comment]
Hi @416serg I am working on this gradually, but it's actually quite chunky. 

Part of the trickiness relates to decide precedence between a start time from the URL and/or clicking on a timestamp link vs using the last played time from localstorage. To make this easier I proposed a refactor to the localstorage code in #415. 

This makes it easier to introduce more logic that plays nice with the localstorage position stuff. Could you have a look at that PR please and let me know if you are happy to merge it?

**Comment by reobin** [comment]
I worked on bullet point no. 2 in #518 if that can interest someone
