### ISSUE TITLE
code blocks aren't visually distinctive

### ISSUE THREAD

**Issue by csellis** [wesbos/Syntax#407]
![Screenshot from 2019-10-03 21-06-29](https://user-images.githubusercontent.com/814405/66174167-b5ce0d80-e621-11e9-8671-87866afa21f7.png)

Usually, they have a darker background that stands out from surrounding text. In this case they're bolder and larger than surrounding text.

**Comment by phernandoe** [comment]
I can take a stab at it. I'll try adding some contrast to the code blocks and see how it looks across different pages.

**Comment by luisaugusto** [comment]
If no one is assigned or working on this, I could get this fixed in the next couple of days.

**Comment by csellis** [comment]
@luisaugusto I already submitted it for a pull at [408](https://github.com/wesbos/Syntax/pull/408). It just needs a review.
