### ISSUE TITLE
[Feature Request] Add localStorage to track the listen spot of a podcast

### ISSUE THREAD

**Issue by jamesbarrett95** [wesbos/Syntax#42]
Problem statement
[] Bug Report
[x] Feature Request

Summary:
Once the application is closed and re-opened, Syntax.fm should store the listen spot of a podcast.

Expected results:
The user returns to Syntax.fm with their last played podcast selected and at the time of when they closed the application.

Actual Results:
When the user revisits the application, the most recently uploaded Podcast is selected, starting at 00:00

Steps to Reproduce
N/A

Environment:
N/A

Additional Information
My friend loves your podcasts too and shares the same frustrations!

**Comment by wesbos** [comment]
Thanks again for implementing this!
