### ISSUE TITLE
Add date (month/day/year?) to the episode's sidebar

### ISSUE THREAD

**Issue by waldothedeveloper** [wesbos/Syntax#449]
### Hey guys happy 2020!
This is a suggestion.
I think it would be a good idea to add the dates of the episodes below the Episode titles (marked in red in the screenshot).
I see that when you click on each episode you can see the date on the upper right (also marked in red in the screenshot) but it takes that one extra click -in my modest opinion- so I think it should be beneficial to have it there as well if you want to look at the dates based on the Episode's titles.
 I love the show btw!

![Screen Shot 2020-01-06 at 9 32 51 PM](https://user-images.githubusercontent.com/16472274/71863865-380c1900-30cc-11ea-8fe0-116ab49e65b0.png)

**Comment by wesbos** [comment]
Yeah this is a good idea. Who wants to implement it?

**Comment by waldothedeveloper** [comment]
I can do a PR if that's ok :)

**Comment by waldothedeveloper** [comment]
ok @wesbos and/or @stolinski 
Let me know if you guys like it like this or if you want a different color accent, some little extra padding, or anything else, if not I'll submit the PR.
I used the "newgrey" from your _show.styl file.

![image](https://user-images.githubusercontent.com/16472274/72961734-1bd0d300-3d80-11ea-868d-4bbfa73d9506.png)


![image](https://user-images.githubusercontent.com/16472274/72961703-05c31280-3d80-11ea-8c8f-0a97677357ee.png)

**Comment by wesbos** [comment]
looks great! please send a PR

**Comment by shayaulman** [comment]
## Little Improvement
Hey @waldothedeveloper, what do you say to this little change?
1. I changed that the episode number and the date should be on the same line.
2. The date - as it is additional info - has a little bit a lighter shade (`gray2`).
<img width="998" alt="Screen Shot 2020-02-06 at 13 26 55" src="https://user-images.githubusercontent.com/47426218/73933133-791e6580-48e4-11ea-9321-e9912d535d65.png">

#### Why I think it's better?
1. The 2 pieces of info are on the same line.
2. This expands less the tab vertically

What do you think? please let me know...
Thanks!

**Comment by wesbos** [comment]
I like it! Send a PR?

**Comment by waldothedeveloper** [comment]
Wow, that looks very cool now!
@shayaulman with two more tweaks we have a startup idea LOL...
Thank you guys
