### ISSUE TITLE
Add Link To Reddit Community

### ISSUE THREAD

**Issue by stolinski** [wesbos/Syntax#456]
https://www.reddit.com/r/SyntaxFM/

**Comment by sw-yx** [comment]
👀

**Comment by domemvs** [comment]
@stolinski Do you have any idea where to put it and how prominent?

**Comment by matoval** [comment]
I added a link to the Syntax Reddit community under the syntax logo. I centered it on both desktop and mobile. I created PR #500 for this issue. I wasn't sure where the link should go so I hope you like it under the logo.
