### ISSUE TITLE
Site Player Won’t Run, Time is 00:0NaN

### ISSUE THREAD

**Issue by varlevi** [wesbos/Syntax#511]
On the site, none of the episodes will play, and the time is stuck at 00:0NaN. In addition, none of the episodes will play on Apple Podcasts, although their titles and details still do show up. Ihave not tried other podcast players.

**Comment by wesbos** [comment]
Hmm let me take a look! Thanks :)

**Comment by wesbos** [comment]
Bah - Zeit/ Vercel stopped working with Version 1.0. Gotta move it over

**Comment by varlevi** [comment]
☹️ 

All those dependencies...

**Comment by varlevi** [comment]
Hmm... following the recent commit, I’m still unable to play any episode on the site or podcasts app. Of course, I’m assuming that fix was meant to fix this problem, but you may still be working on it. If so, that’s fine. Just wanted to make sure you knew. 😉

**Comment by wesbos** [comment]
This should be fixed now! Please re-open if it's still an issue :)
