### ISSUE TITLE
Wrongly formatted show notes for newest episode "our react wish list" on pocket casts

### ISSUE THREAD

**Issue by hedythedev** [wesbos/Syntax#515]
As the title says the show notes seems wrongly formatted on pocket casts

![Screenshot_20200701_212641_au com shiftyjelly pocketcasts](https://user-images.githubusercontent.com/50042066/86249420-d02c1c00-bb9e-11ea-8c71-889dfa1fa615.jpg)

**Comment by wesbos** [comment]
thanks - let me take a look!

**Comment by wesbos** [comment]
just updated it - should fix it. thanks!
