### ISSUE TITLE
Inconsistent Focus Styles in Show Notes

### ISSUE THREAD

**Issue by garyb1** [wesbos/Syntax#568]
In the show notes, I noticed different styles being applied to buttons on the same row. One focus style is the blue focus ring and then the other has a thin dotted style.

<img width="606" alt="Screenshot 2020-11-23 at 11 22 32" src="https://user-images.githubusercontent.com/12486130/99956665-4dd70b00-2d7e-11eb-94f5-d994fc94b6b8.png">

Is thin dotted the correct focus style for these buttons?

See reply below

**Comment by garyb1** [comment]
The difference is that the first item is a button and the others are anchors. which makes sense in terms of behavious, as a button is performing the action, and the anchor is sending the user away to a different page. 

<img width="225" alt="Screenshot 2020-11-23 at 11 28 11" src="https://user-images.githubusercontent.com/12486130/99957137-174dc000-2d7f-11eb-8164-3c4e7aa80ffb.png">

If this is desired behaviour, I can close this issue. Thanks

**Comment by stolinski** [comment]
Will be fixed in new website.
