### ISSUE TITLE
Logo Proposal for Syntax

### ISSUE THREAD

**Issue by area55git** [wesbos/Syntax#57]
Hi, I'm a graphic designer and I like to collaborate with open source projects. Would you like me to design a Logo for Syntax?

**Comment by wesbos** [comment]
Hey! We already have one - do you not like it?

**Comment by area55git** [comment]
If I like it, I would not change it, I sent you the proposal because I had not seen it. If you need a design for another project you can contact me and I will gladly collaborate.

**Comment by wesbos** [comment]
thank you :)
