### ISSUE TITLE
add link to Potluck Submission Form

### ISSUE THREAD

**Issue by wesbos** [wesbos/Syntax#71]
https://docs.google.com/forms/d/e/1FAIpQLSfQlAo1wXHiJMySdU-h8QMtfoz92aMS9eycEHXB6eRCLh8KHA/viewform

**Comment by wesbos** [comment]
Some sort of button at/near the top of the site?

**Comment by ckujawa** [comment]
might need some help (I'm on lesson 4 of your React for Begginers) but I'll grab this and work on it

**Comment by abiclub23** [comment]
@ckujawa - I picked this up earlier today, but I forgot to leave a comment here. I did a quick mock up below to get some ideas going. I am happy to help you. 

@wesbos @ckujawa- Feels like there are already a lot of buttons  in the header, I added it as a link for starters. What do you guys think ?

Desktop
<img width="1033" alt="image" src="https://user-images.githubusercontent.com/6979452/41751935-0170eef8-7579-11e8-9f26-7459c30515da.png">

mWeb
<img width="354" alt="image" src="https://user-images.githubusercontent.com/6979452/41751952-1bcb451e-7579-11e8-8d8a-94bf27d47a1a.png">

**Comment by abiclub23** [comment]
Version -2   - A ribbon on top left/right, its a more prominent callout

<img width="1164" alt="image" src="https://user-images.githubusercontent.com/6979452/41752166-a7a02996-757a-11e8-8f09-7b56374602e9.png">

**Comment by ckujawa** [comment]
@abiclub23 lol...I had almost completed it last night before seeing this. I am not at that machine last night so I can't post screen shots of what I've done (I'm at the day job right now so it will be about 6 hours before I can) but I had put a button below the podcast links to the right of the header--but I personally really like the diagonal button above--it jumps right out at you. 

I've also got the form pretty much done (there's one thing I'm stuck on...how to do the cool animation of the bottom border fading in to black from the center. 

all that said...what would you think about teaming up and combining your button ideas with the form page that I've been working on (honestly, that's been the bulk of my work)

@wesbos: The big question I had is what to do with the form data once the user hits submit. Email the data to you guys...or did you have something else in mind?

**Comment by wesbos** [comment]
Thanks everyone! I like the text based "ask us a question" in the last screenshot.

The form is a google form which will submit and go into a spreadsheet - thats how Scott and I keep track of them, so no need to have them email or anything like that.

**Comment by abiclub23** [comment]
@wesbos @ckujawa - my understanding is we just need to link to the form , we don’t actually need to build the form. Correct me if I am wrong.

If we go with the ‘ask us a question’  in mWeb it will wrap under the title text is that fine ?

**Comment by abiclub23** [comment]
@wesbos - Raised a PR https://github.com/wesbos/Syntax/pull/86.
