### ISSUE TITLE
Add link to Google Podcasts

### ISSUE THREAD

**Issue by wesbos** [wesbos/Syntax#76]
Lots of people searching "Syntax fm" on google podcast, but that isn't the name of it. We should link it directly from the website.

A few questions for android folk

1. Is google play for podcasts still a thing?
1. Is there a link to syntax on android?

**Comment by francisprovost** [comment]
@wesbos For your questions
1. Google will phase out Google Play Music in favor of youtube music. Podcasts will probably be "Google Podcasts" only. For now it still alive
2. For the links, there's no "Share" button in the app 

weirdly "Syntax fm podcast" doesn't work but "Syntax fm google podcast" does for me ¯\_(ツ)_/¯

**Comment by ekaoddlass** [comment]
Got it, going to work on it in a bit.
