### ISSUE TITLE
Add Spotify Link to our podcast

### ISSUE THREAD

**Issue by wesbos** [wesbos/Syntax#77]
Spotify is becoming more popular for listening to our podcast. 

Here is the link to ours: 

https://open.spotify.com/show/4kYCRYJ3yK5DQbP5tbfZby?si=bOe7-kl6RnOHapMsVnFWgw

We will also need a new icon and have to figure out how to fit the links in with #76

**Comment by ekaoddlass** [comment]
Hi Wes, I'd like to have a go at this (along with #76) please.
The Spotify & Google Podcast buttons would be alongside existing buttons (something like below) — or do you have any other consideration? 
![screen shot 2018-06-21 at 9 46 08 pm](https://user-images.githubusercontent.com/6597211/41726516-8ca48688-759c-11e8-9bd3-4234a5809dcd.png)

**Comment by wesbos** [comment]
I think we should go ahead and do this 100% width since the number of buttons keep growing. 

@ekaoddlass  Can you update to master as the spotify button has already been added, and then move this down and add Google Podcasts?

**Comment by ekaoddlass** [comment]
Sure @wesbos , I'll make a new fork (with the newly added Spotify button) and implement this.
