### ISSUE TITLE
Timestamps aren't linking to the correct episode

### ISSUE THREAD

**Issue by Christopher-Stevers** [wesbos/Syntax#887]
Looks like clicking on timestamps of episodes that aren't the top one is changing the player, but its just changing where in the player it is instead of changing the episode that's in the player as well.
Here's a gif of the unexpected behaviour:
![timestampFail](https://user-images.githubusercontent.com/72156679/220426755-2b1a8253-807d-4f9e-bf1c-f7856598e1a8.gif)

**Comment by wesbos** [comment]
Oh yeah, it should probably play that episode as well - good catch. Should be simple to do

**Comment by HerrBertling** [comment]
Ha, I just ran into this and checked whether there was an issue open already 😄 Took me too many clicks to understand what was going on :joy:

In my case, I even had a timestamp that exceeded the length of the currently selected episode, so nothing at all happened.

**Comment by iChris** [comment]
> n my case, I even had a timestamp that exceeded the length of the currently selected episode, so nothing at all happened.

Do you remember which episode that was where the timestamp exceeded the episode length? I'm wondering if my [timecode conversion tool](https://codepen.io/iChris/full/ZmeVwN/) is messing up episodes that go past an hour.

**Comment by wesbos** [comment]
@iChris  It's likely someone is playing 1 episode, while viewing the show notes for another episode. Clicking on a timestamp doesn't switch to the curently viewed podcast - it just jumps the currently playing one. Will have to fix that!

**Comment by HerrBertling** [comment]
> Do you remember which episode that was where the timestamp exceeded the episode length?

Oh, it wasn't that the timestamp was not found in the episode it was mentioned in. It tried to find the timestamp in a different episode because a click on a timestamp doesn't select the actually referenced episode.

**Comment by wesbos** [comment]
fixed! Should be live in a few mins
