### ISSUE TITLE
Add guest metadata to all shows with guests

### ISSUE THREAD

**Issue by wesbos** [wesbos/Syntax#926]
an example on this one is done: https://github.com/wesbos/Syntax/blob/master/shows/604%20-%20Supper%20ESLint.md

A single guest can look like this:

```md
---
number: 604
title: Supper Club × ESLint with Nicholas Zakas
date: 1682078400507
url: https://traffic.libsyn.com/syntax/Syntax_-_604.mp3
guest:
  name: Nicholas Zakas
  github: nzakas
  twitter: slicknet
  url: https://humanwhocodes.com/blog/
  social: https://someotherplatform.com
---
```

Multiple guests can be indented and prefixed with `-`. 

Note how social can also be a single url, or list of urls

```md
guest:
  - name: Nicholas Zakas
    github: nzakas
    twitter: slicknet
    url: https://humanwhocodes.com/blog/
    social: https://fosstodon.org/@nzakas
  - name: Guest Two
    github: twoooo
    twitter: heheehe
    url: https://cool.com/blog/
    social: 
      - https://fosstodon.org/@two
      - https://coolmastadon.org/@anotherone
``` 

Here is an incomplete list of guests that was generated a few months back:

- [ ] Show 164 - Harry Dry
- [ ] Show 236 - Dr. Courtney Tolinski
- [ ] Show 264 - Jerome Hardaway
- [ ] Show 298 - Josh Comeau
- [ ] Show 302 - Benjamin Dunphy
- [ ] Show 310 - Brian Leroux
- [ ] Show 330 - Tanner Linsley
- [ ] Show 340 - Matt Holt
- [ ] Show 362 - Miriam Suzanne
- [ ] Show 374 - Chris Coyier and Dave Rupert
- [x] Show 457 - Victor Savkin
- [ ] Show 460 - Jared Palmer
- [ ] Show 463 - Tom Preston-Werner
- [ ] Show 466 - Anselm Hannemann
- [ ] Show 469 - Connor Finlayson
- [ ] Show 472 - Eduardo Bouças
- [ ] Show 475 - Tim Leland
- [ ] Show 478 - Shawn Wang
- [ ] Show 481 - Pokey Rule
- [ ] Show 484 - Kristi Perreault
- [ ] Show 487 - Adam Cowley
- [ ] Show 490 - Syed Balkhi
- [ ] Show 493 - Lee Robinson
- [ ] Show 496 - Josh Larson
- [ ] Show 499 - Rich Harris
- [ ] Show 502 - Brandon Roberts
- [x] Show 505 - Steve Ruiz
- [x] Show 508 - The Primeagan
- [ ] Show 511 - Thomas Mann
- [ ] Show 514 - Hursh Agrawal
- [ ] Show 517 - bdougie
- [ ] Show 520 - Nikolas Burk
- [ ] Show 523 - TJ DeVries
- [ ] Show 526 - Alex KATT Johansson
- [ ] Show 529 - Filipe Ferreira
- [ ] Show 532 - Dr. Courtney Tolinski
- [ ] Show 538 - Ryan Dahl
- [ ] Show 544 - Jared Sumner
- [ ] Show 547 - Vu Le
- [ ] Show 550 - Jonny Burger
- [ ] Show 553 - Kenneth Lyerly
- [ ] Show 556 - Kilian Valkhof
- [ ] Show 559 - Sarah Drasner
- [ ] Show 562 - Katherine Mello
- [ ] Show 565 - Simen Svale Skogsrud and Espen Hovlandsdal
- [ ] Show 568 - Caleb Porzio
- [ ] Show 571 - Tim McNamara
- [ ] Show 574 - Miško Hevery
- [ ] Show 577 - Ryan Carniato
- [ ] Show 580 - Fred Schott
- [x] Show 583 - Steve Sewell

**Comment by bl0om** [comment]
on it

**Comment by iChris** [comment]
From another client's tech podcast experience with guest metadata, I'd suggest using "social media" or something more generic than Twitter, as more guests are opting to use Mastodon or something else as their key social media contact point. 

At least naming the frontend display of the "twitter" metadata point something more generic anyway.

**Comment by wesbos** [comment]
good point - Ill open it up to add an array of other socials as well. The twitter key will stay as Ill use that to try pull in an avatar

**Comment by stolinski** [comment]
<img width="876" alt="Screenshot 2023-04-21 at 9 25 35 AM" src="https://user-images.githubusercontent.com/669383/233675138-febda11a-b912-42fe-b04e-bac4834f4806.png">

Unrelated and hilarious. Github is seeing all of these show numbers as references.

**Comment by wesbos** [comment]
It did initially link them to issues, but the tasks are the checkboxes I have the above thread. It converts them to tasks
