### ISSUE TITLE
Wes' photo doesn't display on Firefox with tracking protection enabled

### ISSUE THREAD

**Issue by sesneaky** [wesbos/Syntax#95]
Firefox version 61.0.1
Tracking protection turned on via Preferences > Privacy & Security

Console output:
```
The resource at "https://pbs.twimg.com/profile_images/877525007185858562/7G9vGTca_400x400.jpg" was blocked because tracking protection is enabled.
```

Visual:
![image](https://user-images.githubusercontent.com/7118950/42398726-3cdf79ca-816b-11e8-915b-c5058ae1d0b8.png)

I'm guessing tracking protection doesn't like the domain?

Cheers,

Sé

**Comment by jaredcaraway** [comment]
@sesneaky That's correct - [check out this issue](https://github.com/mozilla/blok/issues/187). 

I don't know if this would be overkill, but possible solution may be create a cron job that pulls the most recent avatars via Twitter's API to Syntax's assets so the images aren't served from a blocked domain. (I'm sure there's a simpler solution that I am looking right past.)

**Comment by wesbos** [comment]
how about we just save the images in the repo so we don't ping twitter? It's bit us in the past when one of us changes our avatar

**Comment by jaredcaraway** [comment]
@wesbos That's definitely the simpler route! I wasn't sure if you guys were trying to automatically sync your avatars.
